Return events/alerts from signalflow events/alerts queries
signalfx/signalfx-go pull request #118
Opened 2021-01-26 23:02 UTC by scottlepp

Support running signal flow queries like:
```
D = alerts(detector_name='Deployment').publish(label='D')
F = events(eventType='deployment').publish(label='F')
```

2021-01-27 16:24 UTC, keitwb commented on signalflow/computation.go
> +	return c.events
This need to be synchronized and waited on like all the other methods that return execution metadata, such as https://github.com/signalfx/signalfx-go/blob/master/signalflow/computation.go#L117.

2021-01-27 16:25 UTC, keitwb requested changes
See comment.

2021-01-28 14:04 UTC, scottlepp commented
@keitwb updated

2021-01-28 14:23 UTC, keitwb approved these changes
Looks good, thanks for  adding  this.

2021-01-28 14:23 UTC, merged